version: '3.8'

services:
  optimize-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: optimize-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - ./demo_data_medium.csv:/app/demo_data_medium.csv:ro
      - ./demo_data_small.csv:/app/demo_data_small.csv:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  optimize-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: optimize-client
    ports:
      - "8080:80"
    depends_on:
      optimize-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: optimize-network
